// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.2
// source: microservice/micropb/repo.proto

package micropb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendRequestMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *SendRequestMessage) Reset() {
	*x = SendRequestMessage{}
	mi := &file_microservice_micropb_repo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRequestMessage) ProtoMessage() {}

func (x *SendRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_microservice_micropb_repo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRequestMessage.ProtoReflect.Descriptor instead.
func (*SendRequestMessage) Descriptor() ([]byte, []int) {
	return file_microservice_micropb_repo_proto_rawDescGZIP(), []int{0}
}

func (x *SendRequestMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SendResponseMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *SendResponseMessage) Reset() {
	*x = SendResponseMessage{}
	mi := &file_microservice_micropb_repo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResponseMessage) ProtoMessage() {}

func (x *SendResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_microservice_micropb_repo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResponseMessage.ProtoReflect.Descriptor instead.
func (*SendResponseMessage) Descriptor() ([]byte, []int) {
	return file_microservice_micropb_repo_proto_rawDescGZIP(), []int{1}
}

func (x *SendResponseMessage) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type ReceiveRequestMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ReceiveRequestMessage) Reset() {
	*x = ReceiveRequestMessage{}
	mi := &file_microservice_micropb_repo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveRequestMessage) ProtoMessage() {}

func (x *ReceiveRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_microservice_micropb_repo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveRequestMessage.ProtoReflect.Descriptor instead.
func (*ReceiveRequestMessage) Descriptor() ([]byte, []int) {
	return file_microservice_micropb_repo_proto_rawDescGZIP(), []int{2}
}

func (x *ReceiveRequestMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ReceiveResponseMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *ReceiveResponseMessage) Reset() {
	*x = ReceiveResponseMessage{}
	mi := &file_microservice_micropb_repo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveResponseMessage) ProtoMessage() {}

func (x *ReceiveResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_microservice_micropb_repo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveResponseMessage.ProtoReflect.Descriptor instead.
func (*ReceiveResponseMessage) Descriptor() ([]byte, []int) {
	return file_microservice_micropb_repo_proto_rawDescGZIP(), []int{3}
}

func (x *ReceiveResponseMessage) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_microservice_micropb_repo_proto protoreflect.FileDescriptor

var file_microservice_micropb_repo_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x6d,
	0x69, 0x63, 0x72, 0x6f, 0x70, 0x62, 0x2f, 0x72, 0x65, 0x70, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0c, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22,
	0x2e, 0x0a, 0x12, 0x73, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22,
	0x2d, 0x0a, 0x13, 0x73, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x31,
	0x0a, 0x15, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0x30, 0x0a, 0x16, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x32, 0x6a, 0x0a, 0x12, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x65,
	0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x54, 0x0a, 0x0b, 0x73, 0x65, 0x6e,
	0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x20, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x73, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x21, 0x2e, 0x6d, 0x69, 0x63,
	0x72, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x73, 0x65, 0x6e, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x32,
	0x77, 0x0a, 0x16, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76,
	0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x5d, 0x0a, 0x0e, 0x72, 0x65, 0x63,
	0x65, 0x69, 0x76, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x23, 0x2e, 0x6d, 0x69,
	0x63, 0x72, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x72, 0x65, 0x63, 0x65, 0x69,
	0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x1a, 0x24, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x42, 0x16, 0x5a, 0x14, 0x6d, 0x69, 0x63, 0x72,
	0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_microservice_micropb_repo_proto_rawDescOnce sync.Once
	file_microservice_micropb_repo_proto_rawDescData = file_microservice_micropb_repo_proto_rawDesc
)

func file_microservice_micropb_repo_proto_rawDescGZIP() []byte {
	file_microservice_micropb_repo_proto_rawDescOnce.Do(func() {
		file_microservice_micropb_repo_proto_rawDescData = protoimpl.X.CompressGZIP(file_microservice_micropb_repo_proto_rawDescData)
	})
	return file_microservice_micropb_repo_proto_rawDescData
}

var file_microservice_micropb_repo_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_microservice_micropb_repo_proto_goTypes = []any{
	(*SendRequestMessage)(nil),     // 0: microservice.sendRequestMessage
	(*SendResponseMessage)(nil),    // 1: microservice.sendResponseMessage
	(*ReceiveRequestMessage)(nil),  // 2: microservice.receiveRequestMessage
	(*ReceiveResponseMessage)(nil), // 3: microservice.receiveResponseMessage
}
var file_microservice_micropb_repo_proto_depIdxs = []int32{
	0, // 0: microservice.serviceSendMessage.sendMessage:input_type -> microservice.sendRequestMessage
	2, // 1: microservice.serviceReceivedMessage.receiveMessage:input_type -> microservice.receiveRequestMessage
	1, // 2: microservice.serviceSendMessage.sendMessage:output_type -> microservice.sendResponseMessage
	3, // 3: microservice.serviceReceivedMessage.receiveMessage:output_type -> microservice.receiveResponseMessage
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_microservice_micropb_repo_proto_init() }
func file_microservice_micropb_repo_proto_init() {
	if File_microservice_micropb_repo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_microservice_micropb_repo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_microservice_micropb_repo_proto_goTypes,
		DependencyIndexes: file_microservice_micropb_repo_proto_depIdxs,
		MessageInfos:      file_microservice_micropb_repo_proto_msgTypes,
	}.Build()
	File_microservice_micropb_repo_proto = out.File
	file_microservice_micropb_repo_proto_rawDesc = nil
	file_microservice_micropb_repo_proto_goTypes = nil
	file_microservice_micropb_repo_proto_depIdxs = nil
}
